### ISSUE TITLE
Can't run this project in local android devices

### ISSUE THREAD

**Issue by PeaceAntoHim** [revtel/react-native-nfc-rewriter#27]
Hi I got a problem when I want to run this project, I just run `react-native run-android then i got this error

`error Failed to launch emulator. Reason: No emulators found as an output of `emulator -list-avds`.
warn Please launch an emulator manually or connect a device. Otherwise app may fail to launch.
info Installing the app...
Starting a Gradle Daemon (subsequent builds will be faster)

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.9/userguide/command_line_interface.html#sec:command_line_warnings

FAILURE: Build failed with an exception.

* Where:
Build file 'C:\Users\user01\Documents\Absensi-Apps\react-native-nfc-rewriter\node_modules\react-native-reanimated\android\build.gradle' line: 89

* What went wrong:
A problem occurred configuring project ':react-native-reanimated'.
> SDK location not found. Define location with an ANDROID_SDK_ROOT environment variable or by setting the sdk.dir path in your project's local properties file at 'C:\Users\user01\Documents\Absensi-Apps\react-native-nfc-rewriter\android\local.properties'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 42s

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup.
Error: Command failed: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081

FAILURE: Build failed with an exception.

* Where:
Build file 'C:\Users\user01\Documents\Absensi-Apps\react-native-nfc-rewriter\node_modules\react-native-reanimated\android\build.gradle' line: 89

* What went wrong:
A problem occurred configuring project ':react-native-reanimated'.
> SDK location not found. Define location with an ANDROID_SDK_ROOT environment variable or by setting the sdk.dir path in your project's local properties file at 'C:\Users\user01\Documents\Absensi-Apps\react-native-nfc-rewriter\android\local.properties'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 42s

    at makeError (C:\Users\user01\Documents\Absensi-Apps\react-native-nfc-rewriter\node_modules\@react-native-community\cli-platform-android\node_modules\execa\index.js:174:9)
    at C:\Users\user01\Documents\Absensi-Apps\react-native-nfc-rewriter\node_modules\@react-native-community\cli-platform-android\node_modules\execa\index.js:278:16
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async runOnAllDevices (C:\Users\user01\Documents\Absensi-Apps\react-native-nfc-rewriter\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\runOnAllDevices.js:106:5)
    at async Command.handleAction (C:\Users\user01\Documents\Absensi-Apps\react-native-nfc-rewriter\node_modules\@react-native-community\cli\build\index.js:192:9)
info Run CLI with --verbose flag for more details.`

**Comment by PeaceAntoHim** [comment]
> You need to install the Android Studio, Android SDK and the Java Development Kit. Check the steps described here: https://reactnative.dev/docs/environment-setup

Thank's for your help
